In [2]:
import numpy as np

np.array([1,2,3])

array([1, 2, 3])

In [5]:
import numpy as np
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.linspace(1,10,num=4) #等间隔一维数组

array([ 1.,  4.,  7., 10.])

In [16]:
np.random.rand(2,3) #二维随机数组

array([[0.43257003, 0.18611413, 0.77945087],
       [0.49441593, 0.25057032, 0.54553804]])

In [17]:
np.random.randint(5,size=(2,3))

array([[0, 4, 0],
       [0, 2, 4]])

In [20]:
np.fromfunction(lambda i,j:i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [24]:
a = np.array([10,20,30,40,50])
b = np.arange(1,6)
a,b

(array([10, 20, 30, 40, 50]), array([1, 2, 3, 4, 5]))

In [25]:
a+b

array([11, 22, 33, 44, 55])

In [26]:
a-b

array([ 9, 18, 27, 36, 45])

In [27]:
a*b

array([ 10,  40,  90, 160, 250])

In [28]:
a/b

array([10., 10., 10., 10., 10.])

In [29]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A,B

(array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]))

In [30]:
A+B

array([[ 6,  8],
       [10, 12]])

In [31]:
A-B

array([[-4, -4],
       [-4, -4]])

In [32]:
A*B

array([[ 5, 12],
       [21, 32]])

In [33]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [34]:
np.mat(A)*np.mat(B) 
# 如果使用 np.mat 将二维数组准确定义为矩阵，就可以直接使用 * 完成矩阵乘法计算


matrix([[19, 22],
        [43, 50]])

In [35]:
2*A

array([[2, 4],
       [6, 8]])

In [37]:
A.T #转置

array([[1, 3],
       [2, 4]])

In [38]:
np.linalg.inv(A) #求逆

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [39]:
print(a)
np.sin(a)

[10 20 30 40 50]


array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

---
2019年8月6日
《利用Python进行数据分析》第四章 Numpy基础

In [5]:
import numpy as np

data1 = [1,2,3.5,4,5]
arr1 = np.array(data1)
arr1

array([1. , 2. , 3.5, 4. , 5. ])

In [6]:
data2 = [[1,2,3,4],[2,2,3,4]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [2, 2, 3, 4]])

In [7]:
arr2.ndim #二维数组

2

In [8]:
arr2.shape

(2, 4)

In [9]:
arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int64')

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr = np.array([1.5,2.3,6.6])
arr.dtype

dtype('float64')

In [14]:
int_arr = arr.astype('int64')
int_arr

array([1, 2, 6])

In [15]:
arr3d = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
arr3d

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [16]:
arr3d[0]

array([[1, 1, 1],
       [2, 2, 2]])

In [17]:
arr3d[0,1] 

array([2, 2, 2])

In [25]:
arr3d[:2,1:]

array([[[2, 2, 2]],

       [[4, 4, 4]]])

In [27]:
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [28]:
arr2d[:2,1:]=9
arr2d

array([[1, 9, 9],
       [4, 9, 9]])